package lotto.view;

import java.util.List;
import java.util.Map;
import lotto.model.Lotto;

public class OutputView {

    public void printAutoGeneratedLottoNumbers(int lottoCount, List<Lotto> generatedLottoNumbers) {
        printLottoCount(lottoCount);
        printGeneratedLottoNumbers(generatedLottoNumbers);
    }

    public void printWinningStatistics(Map<Integer, Integer> lottoStatistics) {
        System.out.println("당첨 통계");
        System.out.println("---");
        printStatisticsDetails(lottoStatistics);// 일치 숫자 개수 별 몇 개인지 출력
    }

    public void printRateOfReturn(double rateOfReturn) {
        System.out.println("총 수익률은 " + rateOfReturn);
    }

    private void printLottoCount(int lottoCount) {
        System.out.println(lottoCount + "개를 구매했습니다.");
    }

    // 각 로또 번호 출력
    private void printGeneratedLottoNumbers(List<Lotto> generatedLottoNumbers) {
        for (Lotto generatedLottoNumber : generatedLottoNumbers) {
            System.out.println(generatedLottoNumber.getNumbers()); // 로또 형태로 출력
        }
    }

    // 일치 숫자 개수 별 몇 개인지 출력
    private void printStatisticsDetails(Map<Integer, Integer> lottoStatistics) {
        System.out.printf("3개 일치 (5,000원) - %d개%n", lottoStatistics.get(3));
        System.out.printf("4개 일치 (50,000원) - %d개%n", lottoStatistics.get(4));
        System.out.printf("5개 일치 (1,500,000원) - %d개%n", lottoStatistics.get(5));
        System.out.printf("5개 일치, 보너스 볼 일치 (30,000,000원) - %d개%n", lottoStatistics.get(7));
        System.out.printf("6개 일치 (2,000,000,000원) - %d개%n", lottoStatistics.get(6));
    }



}
