package lotto.view;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import lotto.model.Lotto;
import lotto.model.LottoPrize;

public class OutputView {

    public void printAutoGeneratedLottoNumbers(int lottoCount, List<Lotto> generatedLottoNumbers) {
        printLottoCount(lottoCount);
        printGeneratedLottoNumbers(generatedLottoNumbers);
        System.out.println();
    }

    public void printWinningStatistics(Map<Integer, Integer> lottoStatistics) {
        System.out.println("당첨 통계");
        System.out.println("---");
        printStatisticsDetails(lottoStatistics);
    }

    public void printRateOfReturn(double rateOfReturn) {
        System.out.println("총 수익률은 " + rateOfReturn + "%입니다.");
        System.out.println();
    }

    private void printLottoCount(int lottoCount) {
        System.out.println(lottoCount + "개를 구매했습니다.");
    }

    private void printGeneratedLottoNumbers(List<Lotto> generatedLottoNumbers) {
        for (Lotto generatedLottoNumber : generatedLottoNumbers) {
            System.out.println(generatedLottoNumber.getNumbers()); // 로또 형태로 출력
        }
    }

    private void printStatisticsDetails(Map<Integer, Integer> lottoStatistics) {
        for (LottoPrize prize : LottoPrize.values()) {
            int count = Optional.ofNullable(lottoStatistics.get(prize.ordinal() + 3)).orElse(0); // 3부터 시작하는 매칭 수
            System.out.printf("%s - %d개%n", prize.formatMessage(), count);
        }
    }
}
