package lotto.service;


import java.util.List;
import lotto.model.AutoLottoGenerator;
import lotto.model.Lotto;
import lotto.model.LottoMatcher;
import lotto.model.YieldCalculator;
import lotto.util.LottoNumberParser;

public class LottoService {
    private final LottoNumberParser lottoNumberParser;
    private final AutoLottoGenerator autoLottoGenerator;
    private final LottoMatcher lottoMatcher;
    private final YieldCalculator yieldCalculator;

    public LottoService(LottoNumberParser lottoNumberParser, AutoLottoGenerator autoLottoGenerator,
                        LottoMatcher lottoMatcher, YieldCalculator yieldCalculator) {
        this.lottoNumberParser = lottoNumberParser;
        this.autoLottoGenerator = autoLottoGenerator;
        this.lottoMatcher = lottoMatcher;
        this.yieldCalculator = yieldCalculator;
    }

    public List<Lotto> generateLottos(int lottoCount) {
        return autoLottoGenerator.generate(lottoCount);
    }

    public Lotto parseLottoNumbers(String lottoNumbers) {
        return lottoNumberParser.parse(lottoNumbers);
    }

    public void determineWinningDetails(List<Lotto> autoGeneratedLottos, Lotto lottoNumbers, Integer bonusNumber) {
        lottoMatcher.determineWinningDetails(autoGeneratedLottos, lottoNumbers, bonusNumber);
    }

    public String calculateYield(int lottoCount) {
        return yieldCalculator.calculate(lottoCount);
    }
}
