package lotto.model;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.List;
import org.junit.jupiter.api.Test;

class AutoLottoGeneratorTest {


    AutoLottoGenerator autoLottoGenerator = new AutoLottoGenerator();

    @Test
    void 구매_금액에_맞게_로또를_성성한다() {
        int lottoCount = 8;

        List<Lotto> autoGeneratedLottos = autoLottoGenerator.generate(lottoCount);

        assertThat(autoGeneratedLottos).hasSize(lottoCount);

    }

}