package lotto.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.List;
import org.junit.jupiter.api.Test;

class LottoMatcherTest {

    @Test
    void 자동_로또와_정답_로또를_매칭한다() {

        List<String> autoGeneratedLotto =
                List.of("1,2,3,4,5,6", "7,8,9,10,11,12");
        List<Integer> winningLotto = List.of("1,2,3,4,5,6")

        LottoMatcher lottoMatcher = new LottoMatcher();
        int rank = lottoMatcher.determineRank(autoGeneratedLotto, winningLotto);

        assertEquals(rank, 1);

    }

}