package lotto.model;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.ArrayList;
import java.util.List;
import lotto.util.LottoRank;
import org.junit.jupiter.api.Test;

class LottoMatcherTest {

    @Test
    void 자동_로또와_정답_로또를_매칭한다() {

        Lotto winningLotto = new Lotto(List.of(1,2,3,4,5,6));
        Integer bonusNumber = 7;

        Lotto lotto1 = new Lotto(List.of(1,2,3,4,5,6));
        Lotto lotto2 = new Lotto(List.of(7,8,9,10,11,12));


        List<Lotto> autoGeneratedLotto = new ArrayList<>();
        autoGeneratedLotto.add(lotto1);
        autoGeneratedLotto.add(lotto2);

        LottoMatcher lottoMatcher = new LottoMatcher();
        lottoMatcher.determineWinningDetails(autoGeneratedLotto, winningLotto, bonusNumber);
        int firstRankMatchedLottoCount = LottoRank.FIRST.getMatchLottoCount();

        assertEquals(firstRankMatchedLottoCount, 1);

    }

}