package lotto.controller;

import java.util.List;
import lotto.model.AutoLottoGenerator;
import lotto.model.Lotto;
import lotto.model.LottoBonusNumber;
import lotto.model.LottoCount;
import lotto.model.LottoMatcher;
import lotto.model.YieldCalculator;
import lotto.util.InputValidator;
import lotto.util.LottoNumberParser;
import lotto.util.LottoRank;
import lotto.view.InputView;
import lotto.view.OutputView;

public class LottoController {

    private final InputView inputView;
    private final OutputView outputView;
    private final InputValidator inputValidator;
    private final LottoNumberParser lottoNumberParser;
    private final AutoLottoGenerator autoLottoGenerator;
    private final LottoMatcher lottoMatcher;
    private final YieldCalculator yieldCalculator;


    public LottoController(InputView inputView, OutputView outputView, InputValidator inputValidator,
                           LottoNumberParser lottoNumberParser,
                           AutoLottoGenerator autoLottoGenerator, LottoMatcher lottoMatcher,
                           YieldCalculator yieldCalculator) {
        this.inputView = inputView;
        this.outputView = outputView;
        this.inputValidator = inputValidator;
        this.lottoNumberParser = lottoNumberParser;
        this.autoLottoGenerator = autoLottoGenerator;
        this.lottoMatcher = lottoMatcher;
        this.yieldCalculator = yieldCalculator;
    }

    public void run() {
        int lottoCount = getLottoCount();
        outputView.printPurchasedLottoCount(lottoCount);

        List<Lotto> autoGeneratedLottos = autoLottoGenerator.generate(lottoCount);
        String collectedAutoGeneratedLottos = collectAutoGeneratedLottos(autoGeneratedLottos);
        outputView.printAutoGeneratedLotto(collectedAutoGeneratedLottos);

        Lotto lottoNumbers = getLottoNumbers();
        Integer bonusNumber = getLottoBonusNumber(lottoNumbers);

        lottoMatcher.determineWinningDetails(autoGeneratedLottos, lottoNumbers, bonusNumber);

        outputView.startPrintWinning();
        printWinningDetails();

        String yield = yieldCalculator.calculate(lottoCount);
        outputView.printYield(yield);

    }

    private String collectAutoGeneratedLottos(List<Lotto> autoGeneratedLottos) {
        StringBuilder collectedAutoGeneratedLotto = new StringBuilder();
        for (Lotto autoGeneratedLotto : autoGeneratedLottos) {
            String numbersOfOneLotto = autoGeneratedLotto.getLottoNumbers().toString();
            collectedAutoGeneratedLotto.append(numbersOfOneLotto);
            collectedAutoGeneratedLotto.append("\n");
        }

        return collectedAutoGeneratedLotto.toString();
    }

    private void printWinningDetails() {
        for (LottoRank rank : LottoRank.values()) {
            if (rank == LottoRank.NONE) {
                continue;
            }
            int sameNumberCount = rank.getSameNumberCount();
            String winningPrize = rank.getWinningPrize();
            int matchLottoCount = rank.getMatchLottoCount();
            boolean matchBonus = rank.getMatchBonusNumber();
            outputView.printWinningDetails(sameNumberCount, winningPrize, matchLottoCount, matchBonus);


        }
    }

    private int getLottoCount() {
        String purchaseAmount = inputView.enteredPurchaseAmount();

        try {
            LottoCount lottoCount = new LottoCount(purchaseAmount, inputValidator);
            return lottoCount.getLottoCount();
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
            return getLottoCount();
        }
    }

    private Lotto getLottoNumbers() {
        String lottoNumbers = inputView.enteredLottoNumbers();

        try {
            return lottoNumberParser.parse(lottoNumbers);
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
            return getLottoNumbers();
        }
    }

    private Integer getLottoBonusNumber(Lotto lottoNumbers) {
        String bonusNumber = inputView.enteredLottoBonusNumber();

        try {
            LottoBonusNumber lottoBonusNumber = new LottoBonusNumber(bonusNumber, lottoNumbers, inputValidator);
            return lottoBonusNumber.getLottoBonusNumber();
        } catch (IllegalArgumentException e) {
            System.out.println(e.getMessage());
            return getLottoBonusNumber(lottoNumbers);
        }
    }
}
