package lotto.controller;

import java.util.List;
import java.util.Map;
import lotto.model.Lotto;
import lotto.service.LottoService;
import lotto.validator.BonusNumberValidator;
import lotto.validator.PurchaseAmountValidator;
import lotto.view.InputView;
import lotto.view.OutputView;

public class LottoController {

    private final InputView inputView;
    private final OutputView outputView;
    private final LottoService lottoService;
    private final PurchaseAmountValidator purchaseAmountValidator;
    private final BonusNumberValidator bonusNumberValidator;

    public LottoController(InputView inputView, OutputView outputView, LottoService lottoService,
                           PurchaseAmountValidator purchaseAmountValidator, BonusNumberValidator bonusNumberValidator) {
        this.inputView = inputView;
        this.outputView = outputView;
        this.lottoService = lottoService;
        this.purchaseAmountValidator = purchaseAmountValidator;
        this.bonusNumberValidator = bonusNumberValidator;
    }

    public void run() {
        String purchaseAmount = inputAndValidatePurchaseAmount();
        int lottoCount = calculateLottoCount(purchaseAmount);
        System.out.println();
        List<Lotto> generatedLottoNumbers = generateAutoLottoNumbers(lottoCount);
        printAutoGeneratedLottoNumbers(lottoCount, generatedLottoNumbers);

        Lotto winningLottoNumber = inputAndChangeToLotto();
        System.out.println();

        String bonusNumber = inputAndValidateBonusNumber(winningLottoNumber);
        System.out.println();

        Map<Integer, Integer> lottoStatistics = calculateLottoStatistics(winningLottoNumber, bonusNumber,
                generatedLottoNumbers);
        printStatistics(lottoStatistics);

        int lottoSum = calculateProfits(lottoStatistics);
        double lottoRateOfReturn = lottoRateOfReturn(lottoCount, lottoSum);
        printRateOfReturn(lottoRateOfReturn);
    }

    private String inputAndValidatePurchaseAmount() {
        String purchaseAmount;
        while (true) {
            purchaseAmount = purchaseAmount();
            try {
                validateAmount(purchaseAmount);
                return purchaseAmount;
            } catch (IllegalArgumentException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    private String purchaseAmount() {
        return inputView.inputPurchaseAmount();
    }

    private void validateAmount(String purchaseAmount) {
        purchaseAmountValidator.isValidPurchaseAmount(purchaseAmount);
    }

    private int calculateLottoCount(String purchaseAmount) {
        return lottoService.calculateLottoCount(purchaseAmount);
    }

    private List<Lotto> generateAutoLottoNumbers(int lottoCount) {
        return lottoService.generateAutoLottoNumbers(lottoCount);
    }

    private void printAutoGeneratedLottoNumbers(int lottoCount, List<Lotto> generatedLottoNumbers) {
        outputView.printAutoGeneratedLottoNumbers(lottoCount, generatedLottoNumbers);
    }

    private Lotto inputAndChangeToLotto() {
        String winningNumbers;
        while (true) {
            winningNumbers = inputWinningNumbers();
            try {
                List<Integer> changedWinningNumbers = changeWinningNumbers(winningNumbers);
                return winningNumbersToLotto(changedWinningNumbers);
            } catch (IllegalArgumentException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    private String inputWinningNumbers() {
        return inputView.inputWinningNumbers();
    }

    private List<Integer> changeWinningNumbers(String winningNumbers) {
        return lottoService.changeWinningNumbers(winningNumbers);
    }

    private Lotto winningNumbersToLotto(List<Integer> changedLottoNumbers) {
        return new Lotto(changedLottoNumbers);
    }

    private String inputAndValidateBonusNumber(Lotto winningLottoNumbers) {
        String bonusNumber;
        while (true) {
            bonusNumber = bonusNumber();
            try {
                validateBonusNumber(bonusNumber, winningLottoNumbers);
                return bonusNumber;
            } catch (IllegalArgumentException e) {
                System.out.println(e.getMessage());
            }
        }
    }

    private String bonusNumber() {
        return inputView.inputBonusNumber();
    }

    private void validateBonusNumber(String bonusNumber, Lotto winningLottoNumbers) {
        bonusNumberValidator.validBonusNumber(bonusNumber, winningLottoNumbers);
    }

    private Map<Integer, Integer> calculateLottoStatistics(Lotto winningNumbers, String bonusNumber,
                                                           List<Lotto> generatedLottoNumbers) {
        return lottoService.calculateLottoStatistics(winningNumbers, bonusNumber, generatedLottoNumbers);
    }

    private void printStatistics(Map<Integer, Integer> lottoStatistics) {
        outputView.printWinningStatistics(lottoStatistics);
    }

    private int calculateProfits(Map<Integer, Integer> lottoStatistics) {
        return lottoService.calculateProfits(lottoStatistics);
    }

    private double lottoRateOfReturn(int lottoCount, int lottoSum) {
        return lottoService.calculateRateOfReturn(lottoCount, lottoSum);
    }

    private void printRateOfReturn(double rateOfReturn) {
        outputView.printRateOfReturn(rateOfReturn);
    }


}
